package com.juansanz.domain

data class Movie(
    val id: Long,
    val title: String,
    val voteAverage: Double,
    val voteCount: Int,
    val status: String,
    val releaseDate: String,
    val revenue: Long,
    val runtime: Int,
    val adult: String,
    val backdropPath: String,
    val budget: Long,
    val homepage: String,
    val imdbId: String,
    val originalLanguage: String,
    val originalTitle: String,
    val overview: String,
    val popularity: Double,
    val posterPath: String,
    val tagline: String,
    val genres: List<String>,
    val productionCompanies: List<String>,
    val productionCountries: List<String>,
    val spokenLanguages: List<String>,
    val keywords: List<String>,
    val favorite: Boolean,
)

val movie1 = Movie(
    id = 101,
    title = "The Galactic Wanderer",
    voteAverage = 8.5,
    voteCount = 1547,
    status = "Released",
    releaseDate = "2022-11-15",
    revenue = 98000000,
    runtime = 135,
    adult = "False",
    backdropPath = "https://image.tmdb.org/t/p/w780//zcc0My3G4SYR72VuEYHNcUWkkW0.jpg",
    budget = 150000000,
    homepage = "https://www.galacticwanderer.com",
    imdbId = "tt1234567",
    originalLanguage = "en",
    originalTitle = "The Galactic Wanderer",
    overview = "A space adventurer embarks on a journey to uncover the secrets of the galaxy while battling mysterious foes.",
    popularity = 3200.5,
    posterPath = "https://image.tmdb.org/t/p/w185/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    tagline = "Beyond the stars, lies destiny.",
    genres = listOf("Science Fiction", "Adventure", "Action"),
    productionCompanies = listOf("SpaceDream Productions", "Universal Studios"),
    productionCountries = listOf("United States"),
    spokenLanguages = listOf("English", "Spanish"),
    keywords = listOf("space", "adventure", "galaxy", "hero", "alien"),
    favorite = true,
)

val movie2 = Movie(
    id = 102,
    title = "Shadows of the Past",
    voteAverage = 7.2,
    voteCount = 980,
    status = "Released",
    releaseDate = "2023-05-25",
    revenue = 45000000,
    runtime = 118,
    adult = "False",
    backdropPath = "https://image.tmdb.org/t/p/w780//x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
    budget = 75000000,
    homepage = "https://www.shadowsofthepastmovie.com",
    imdbId = "tt2345678",
    originalLanguage = "en",
    originalTitle = "Shadows of the Past",
    overview = "A detective delves into the mysteries of an unsolved crime, only to find that the answers lie in his own past.",
    popularity = 2100.8,
    posterPath = "https://image.tmdb.org/t/p/w185/ggQ6o8X5984OCh3kZi2UIJQJY5y.jpg",
    tagline = "The truth hides in the darkness.",
    genres = listOf("Thriller", "Drama", "Mystery"),
    productionCompanies = listOf("DarkLight Studios", "Fox Entertainment"),
    productionCountries = listOf("Canada", "United States"),
    spokenLanguages = listOf("English", "French"),
    keywords = listOf("detective", "mystery", "past", "crime", "secrets"),
    favorite = false,
)

val movie3 = Movie(
    id = 103,
    title = "The Emerald Quest",
    voteAverage = 6.8,
    voteCount = 712,
    status = "Released",
    releaseDate = "2021-07-10",
    revenue = 30000000,
    runtime = 122,
    adult = "False",
    backdropPath = "https://image.tmdb.org/t/p/w780//nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    budget = 50000000,
    homepage = "https://www.emeraldquestmovie.com",
    imdbId = "tt3456789",
    originalLanguage = "en",
    originalTitle = "The Emerald Quest",
    overview = "A young explorer sets out on a daring adventure to retrieve a legendary emerald that holds the key to a forgotten civilization.",
    popularity = 1800.4,
    posterPath = "https://image.tmdb.org/t/p/w185/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    tagline = "Some treasures are worth the risk.",
    genres = listOf("Adventure", "Action", "Fantasy"),
    productionCompanies = listOf("Treasure Films", "DreamWorks"),
    productionCountries = listOf("United Kingdom", "United States"),
    spokenLanguages = listOf("English"),
    keywords = listOf("treasure", "emerald", "adventure", "explorer", "civilization"),
    favorite = false,
)
